### ISSUE TITLE
Implement `flamingo/{kind}-replace` to allow the whole spec replace

### ISSUE THREAD

**Issue by chanwit** [flux-subsystem-argo/fsa#15]

**Comment by chanwit** [comment]
new image for testing `ghcr.io/flux-subsystem-argo/fsa/argocd:v2.9.6-fl.23-main-86c4bdb9`

**Comment by chanwit** [comment]
Hi @isugimpy

I've implemented `flamingo/kustomize-replace`, another annotation that might solve your problem.

Instead of override some values, this annotation allow you to override the whole `spec` block. Please let me know if it works for you.

**Comment by chanwit** [comment]
Example

```yaml
apiVersion: v1
kind: Application
metadata:
  name: app-1
  annotations:
    flamingo/kustomize-replace: |
      spec:
        interval: 5m0s
        wait: false
        prune: false
        # ... other fields to complete your KS
```
